name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.x

      - name: Check terraform format
        run: terraform fmt -recursive -check

      - name: Check terraform validate
        run: terraform validate
