name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.x
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup secrets.auto.tfvars
        run: |
          touch secrets.auto.tfvars
          echo 'cloudflare_api_token = "${{ secrets.CLOUDFLARE_API_TOKEN }}"' >> secrets.auto.tfvars

      - name: Check terraform format
        run: terraform fmt -recursive -check -no-color

      - name: Run terraform init
        run: terraform init -no-color

      - name: Check terraform validate
        run: terraform validate -no-color

      - name: Check terraform plan
        run: terraform plan -no-color
